name: Release landingpage image

on:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.owner.id }} == ${{ github.event.sender.id }}

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build Docker image
        run: |
          docker pull ghcr.io/home-assistant/green-homeassistant:landingpage
          docker tag ghcr.io/panther-ha/panther-homeassistant:landingpage
          docker push ghcr.io/panther-ha/panther-homeassistant:landingpage

